// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLZLnqlo7nXztdC1g75Unx39MXX7zrKHo',
    appId: '1:1041669444749:android:c65f0aa474fd1188923ec4',
    messagingSenderId: '1041669444749',
    projectId: 'attendence-26702',
    storageBucket: 'attendence-26702.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASxhxu_Ou1Ln0h8Kx0WfcHQ6ISAgsovu8',
    appId: '1:1041669444749:ios:d41c5b26093caf74923ec4',
    messagingSenderId: '1041669444749',
    projectId: 'attendence-26702',
    storageBucket: 'attendence-26702.firebasestorage.app',
    iosClientId: '1041669444749-guf59d6q71gnam0di4ld730nuiah488v.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminpanel',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOE8y2vCQMU4LwmDMYRXKlxVmiOVeuQBE',
    appId: '1:1041669444749:web:b39c7604975a862a923ec4',
    messagingSenderId: '1041669444749',
    projectId: 'attendence-26702',
    authDomain: 'attendence-26702.firebaseapp.com',
    storageBucket: 'attendence-26702.firebasestorage.app',
    measurementId: 'G-ZPBJC0MMMF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASxhxu_Ou1Ln0h8Kx0WfcHQ6ISAgsovu8',
    appId: '1:1041669444749:ios:d41c5b26093caf74923ec4',
    messagingSenderId: '1041669444749',
    projectId: 'attendence-26702',
    storageBucket: 'attendence-26702.firebasestorage.app',
    iosClientId: '1041669444749-guf59d6q71gnam0di4ld730nuiah488v.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminpanel',
  );
}
